<a href="https://colab.research.google.com/github/DataGF/data-science-python-exercises/blob/master/numpy_arrays_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Arrays

How to initialize NumPy arrays  
Create several NumPy arrays

In [1]:
# import numpy

import numpy as np

# create first array with the np.array() function
# assign float32 data type for its elements
# print the arry with the repr() function

arr = np.array([[10, 11, 12], [13, 14, 15]], dtype=np.float32)
print(repr(arr))

array([[10., 11., 12.],
       [13., 14., 15.]], dtype=float32)


In [2]:
# integers are cast to their floating-point equivalents by default with np.array() function
arr = np.array([10, 11.1, 222])
print(repr(arr))

array([ 10. ,  11.1, 222. ])


In [3]:
# the difference between referencing and copying a array with the copy() function
a = np.array([110, 23])
b = np.array([91, 81])

# c is reference to a
c = a

# the changes made in c is referenced to a as well
print('Array a: {}'.format(repr(a)))
c[0] = 58
print('Array a: {}'.format(repr(a)))
print('Array c: {}'.format(repr(c)))

# d is a copy of b, but not its reference
d = b.copy()
d[0] = 99

# the changes made in d is not referenced to b with this method
print('Array b: {}'.format(repr(b)))
print('Array d: {}'.format(repr(d)))

Array a: array([110,  23])
Array a: array([58, 23])
Array c: array([58, 23])
Array b: array([91, 81])
Array d: array([99, 81])


In [4]:
# casting array data type with astype() function
arr = np.array([0, 1, 2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


In [5]:
# np.nan is a common filter value for incomplete data
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

# result in a ValueError, np.nan can't take integer type
np.array([np.nan, 1, 2], dtype=np.int32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


ValueError: ignored

In [6]:
# infinity in python with the np.inf special value
print(np.inf > 999999999999999999999)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# result in an OverflowError, np.inf can't take integer type
np.array([np.inf, 3], dtype=np.int32)

True
array([inf,  5.])
array([-inf,   1.])


OverflowError: ignored