<a href="https://colab.research.google.com/github/DataGF/data-science-python-exercises/blob/master/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ranged data


In [1]:
# import numpy
import numpy as np

The output of np.arange:

1. If only a single number, n, is passed in as an argument, np.arange will return an array with all the integers in the range [0, n). Note: the lower end is inclusive while the upper end is exclusive.

2. For two arguments, m and n, np.arange will return an array with all the integers in the range [m, n).

3. For three arguments, m, n, and s, np.arange will return an array with the integers in the range [m, n) using a step size of s.

4. Like np.array, np.arange performs upcasting. It also has the dtype keyword argument to manually cast the array.

In [2]:
arr = np.arange(10)
print(repr(arr))

arr = np.arange(10.1)
print(repr(arr))

arr = np.arange(-1, 9)
print(repr(arr))

arr = np.arange(-1.5, 9, 2)
print(repr(arr))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])
array([-1.5,  0.5,  2.5,  4.5,  6.5,  8.5])


To specify the number of elements in the returned array, rather than the step size, we can use the `np.linspace` function.

In [4]:
arr = np.linspace(1, 20, num=5)
print(repr(arr))

arr = np.linspace(7, 21, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(3, 12, num=4, dtype=np.int32)
print(repr(arr))

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])
array([ 7. , 10.5, 14. , 17.5])
array([ 3,  6,  9, 12], dtype=int32)


# Reshaping data

In [17]:
# reshape to any dimension wished
arr = np.arange(8)
print('Original array: {}'.format(repr(arr)), '\n')
reshaped_arr = np.reshape(arr, (2, 4))
print('Original array 2D (2x4): \n {}'.format(repr(reshaped_arr)), '\n')
print('New shape: {}'.format(reshaped_arr.shape), '\n')
reshaped_arr = np.reshape(arr, (-1, 2, 2))
print('Original array 3D (2x2x2): \n {}'.format(repr(reshaped_arr)), '\n')
print('New shape: {}'.format(reshaped_arr.shape))

Original array: array([0, 1, 2, 3, 4, 5, 6, 7]) 

Original array 2D (2x4): 
 array([[0, 1, 2, 3],
       [4, 5, 6, 7]]) 

New shape: (2, 4) 

Original array 3D (2x2x2): 
 array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]]) 

New shape: (2, 2, 2)


In [19]:
# reshape to any dimension wished and flatten to 1D with flatten function
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr), '\n')
print('arr shape: {}'.format(arr.shape), '\n')
print(repr(flattened), '\n')
print('flattened shape: {}'.format(flattened.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]]) 

arr shape: (2, 4) 

array([0, 1, 2, 3, 4, 5, 6, 7]) 

flattened shape: (8,)


# Transposing data

In [20]:
# np.transpose function to transpose data
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


In [25]:
arr = np.arange(24)
print(repr(arr), '\n')
arr = np.reshape(arr, (3, 4, 2))
print(repr(arr), '\n')
print('arr shape: {}'.format(arr.shape), '\n')
transposed = np.transpose(arr, axes=(1, 2, 0))
print(repr(transposed), '\n')
print('transposed arr shape: {}'.format(transposed.shape))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23]) 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]]) 

arr shape: (3, 4, 2) 

array([[[ 0,  8, 16],
        [ 1,  9, 17]],

       [[ 2, 10, 18],
        [ 3, 11, 19]],

       [[ 4, 12, 20],
        [ 5, 13, 21]],

       [[ 6, 14, 22],
        [ 7, 15, 23]]]) 

transposed arr shape: (4, 2, 3)


In this example, the old first dimension became the new third dimension, the old second dimension became the new first dimension, and the old third dimension became the new second dimension. The default value for axes is a dimension reversal (e.g. for 3-D data the default axes value is [2, 1, 0]).

# Zeros and ones

In [26]:
arr = np.zeros(5)
print(repr(arr))

arr = np.ones((4, 5))
print(repr(arr))

arr = np.ones((4, 5), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0., 0.])
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)


If we want to create an array of 0's or 1's with the same shape as another array, we can use `np.zeros_like` and `np.ones_like`.

In [27]:
arr = np.array([[5, 6], [7, 8]])
print(repr(np.zeros_like(arr)))
arr = np.array([[10., 11.], [11.2, 14.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)
